export type Product = {
  id: string;
  slug: string;
  name: string;
  category: string;
  price: number;
  oldPrice?: number;
  rating: number;
  reviews: number;
  stock: number;
  gradient: string;
  badge?: string;
  shortDesc: string;
  description: string;
  specs: { label: string; value: string }[];
};

export const categories = [
  "همه",
  "ویولن",
  "کمان",
  "کیف و جعبه",
  "سیم ویولن",
  "رزین",
  "شانه و چانه‌گیر",
  "نت و آموزش",
];

export const products: Product[] = [
  {
    id: "p1",
    slug: "violon-4-4-ostad",
    name: "ویولن استاد ۴/۴ چوب افرا",
    category: "ویولن",
    price: 18500,
    oldPrice: 21000,
    rating: 4.8,
    reviews: 64,
    stock: 6,
    gradient: "linear-gradient(140deg,#0d9488,#7c93ff)",
    badge: "پرفروش",
    shortDesc: "ویولن دست‌ساز با روکش صیقلی، مناسب هنرجویان سطح متوسط تا پیشرفته.",
    description:
      "این ویولن با چوب افرای انتخابی و روکش صیقلی دست‌ساز تولید شده و صدایی گرم و متعادل در تمام رجیسترها دارد. برای هنرجویانی که از سطح متوسط به بالا هستند و به دنبال ارتقای کیفیت صدا هستند، گزینه‌ی مناسبی است.",
    specs: [
      { label: "اندازه", value: "۴/۴ (بزرگسال)" },
      { label: "جنس بدنه", value: "چوب افرا و صنوبر" },
      { label: "کمان همراه", value: "دارد" },
      { label: "گارانتی", value: "۱۸ ماه" },
    ],
  },
  {
    id: "p2",
    slug: "violon-3-4-koodakan",
    name: "ویولن کودکان ۳/۴",
    category: "ویولن",
    price: 9800,
    rating: 4.6,
    reviews: 41,
    stock: 12,
    gradient: "linear-gradient(140deg,#7c93ff,#0d9488)",
    shortDesc: "سبک و مقاوم، مخصوص هنرجویان نوجوان.",
    description:
      "طراحی‌شده برای دست‌های کوچک‌تر با وزن سبک و کوک پایدار. گزینه‌ای مطمئن برای شروع یادگیری نوجوانان.",
    specs: [
      { label: "اندازه", value: "۳/۴ (نوجوانان)" },
      { label: "جنس بدنه", value: "چوب افرا" },
      { label: "کمان همراه", value: "دارد" },
      { label: "گارانتی", value: "۱۲ ماه" },
    ],
  },
  {
    id: "p3",
    slug: "kaman-hirfeei-brazilwood",
    name: "کمان حرفه‌ای برزیل‌وود",
    category: "کمان",
    price: 4200,
    rating: 4.9,
    reviews: 88,
    stock: 20,
    gradient: "linear-gradient(140deg,#0f766e,#0d9488)",
    badge: "پیشنهاد ویژه",
    shortDesc: "تعادل و کشش دقیق، مناسب اجرای قطعات پیشرفته.",
    description:
      "این کمان از چوب برزیل‌وود با موی طبیعی اسب تولید شده و تعادل دقیقی بین سبکی و کنترل ایجاد می‌کند؛ گزینه‌ای عالی برای نوازندگانی که وارد سطح پیشرفته می‌شوند.",
    specs: [
      { label: "جنس چوب", value: "برزیل‌وود" },
      { label: "نوع مو", value: "موی طبیعی اسب" },
      { label: "وزن", value: "۶۰ گرم" },
      { label: "گارانتی", value: "۶ ماه" },
    ],
  },
  {
    id: "p4",
    slug: "kaman-amoozeshi-fiberglass",
    name: "کمان آموزشی فایبرگلاس",
    category: "کمان",
    price: 1450,
    rating: 4.4,
    reviews: 55,
    stock: 34,
    gradient: "linear-gradient(140deg,#3d4c99,#7c93ff)",
    shortDesc: "مقاوم و مقرون‌به‌صرفه، انتخاب مناسب برای شروع.",
    description: "کمانی مقاوم و باکیفیت برای هنرجویان مبتدی که به دنبال گزینه‌ای مقرون‌به‌صرفه هستند.",
    specs: [
      { label: "جنس چوب", value: "فایبرگلاس" },
      { label: "نوع مو", value: "مصنوعی درجه‌یک" },
      { label: "وزن", value: "۵۸ گرم" },
      { label: "گارانتی", value: "۳ ماه" },
    ],
  },
  {
    id: "p5",
    slug: "jabe-violon-carbon",
    name: "جعبه ویولن کربن سبک",
    category: "کیف و جعبه",
    price: 6900,
    rating: 4.7,
    reviews: 37,
    stock: 15,
    gradient: "linear-gradient(140deg,#1c1c22,#7c93ff)",
    shortDesc: "ضدضربه و فوق‌العاده سبک برای سفرهای طولانی.",
    description: "جعبه‌ای مقاوم در برابر ضربه و رطوبت، با وزن بسیار پایین؛ مناسب برای نوازندگانی که مدام سفر می‌کنند.",
    specs: [
      { label: "جنس بدنه", value: "کامپوزیت کربنی" },
      { label: "وزن", value: "۲.۱ کیلوگرم" },
      { label: "مقاومت", value: "ضدآب و ضدضربه" },
      { label: "گارانتی", value: "۱۲ ماه" },
    ],
  },
  {
    id: "p6",
    slug: "kif-violon-parche-i",
    name: "کیف پارچه‌ای ویولن",
    category: "کیف و جعبه",
    price: 1250,
    rating: 4.2,
    reviews: 29,
    stock: 40,
    gradient: "linear-gradient(140deg,#0f766e,#1c1c22)",
    shortDesc: "سبک، اقتصادی و مناسب جابه‌جایی روزانه.",
    description: "کیفی سبک برای استفاده‌ی روزمره و رفت‌وآمد به کلاس؛ دارای بند قابل‌تنظیم.",
    specs: [
      { label: "جنس", value: "پارچه ضدآب" },
      { label: "وزن", value: "۰.۶ کیلوگرم" },
      { label: "بند حمل", value: "قابل‌تنظیم" },
      { label: "گارانتی", value: "۳ ماه" },
    ],
  },
  {
    id: "p7",
    slug: "sim-violon-dominant",
    name: "سیم ویولن ست کامل درجه‌یک",
    category: "سیم ویولن",
    price: 1650,
    rating: 4.8,
    reviews: 112,
    stock: 60,
    gradient: "linear-gradient(140deg,#0d9488,#0f766e)",
    badge: "پرفروش",
    shortDesc: "صدای گرم و پایداری کوک بالا برای اجرای حرفه‌ای.",
    description: "ست کامل ۴ سیم با پوشش سینتتیک، معروف به پایداری کوک بالا و صدای گرم؛ انتخاب اول بسیاری از نوازندگان حرفه‌ای.",
    specs: [
      { label: "تعداد", value: "ست ۴ سیمی" },
      { label: "جنس مغزی", value: "سینتتیک" },
      { label: "مناسب", value: "ویولن ۴/۴" },
      { label: "گارانتی", value: "تعویض در صورت نقص" },
    ],
  },
  {
    id: "p8",
    slug: "sim-violon-tak-mi",
    name: "سیم تکی می (E) طلایی",
    category: "سیم ویولن",
    price: 380,
    rating: 4.5,
    reviews: 46,
    stock: 80,
    gradient: "linear-gradient(140deg,#7c93ff,#3d4c99)",
    shortDesc: "درخشندگی و وضوح صدا در زیرترین رجیستر.",
    description: "سیم می با روکش طلایی که وضوح و درخشندگی خاصی به صدای زیر ویولن می‌بخشد.",
    specs: [
      { label: "نت", value: "می (E)" },
      { label: "روکش", value: "طلایی" },
      { label: "مناسب", value: "ویولن ۴/۴ و ۳/۴" },
    ],
  },
  {
    id: "p9",
    slug: "rosin-tala-degree-yek",
    name: "رزین طلایی درجه‌یک",
    category: "رزین",
    price: 620,
    rating: 4.6,
    reviews: 73,
    stock: 90,
    gradient: "linear-gradient(140deg,#0f766e,#0d9488)",
    shortDesc: "چسبندگی متعادل، مناسب اقلیم‌های گرم و مرطوب.",
    description: "رزینی با چسبندگی متعادل که گرد و غبار کمتری تولید می‌کند و برای آب‌وهوای گرم مناسب است.",
    specs: [
      { label: "نوع", value: "رزین طلایی (روشن)" },
      { label: "مناسب برای", value: "ویولن و ویولا" },
    ],
  },
  {
    id: "p10",
    slug: "rosin-tireh-zemestani",
    name: "رزین تیره زمستانی",
    category: "رزین",
    price: 590,
    rating: 4.3,
    reviews: 22,
    stock: 70,
    gradient: "linear-gradient(140deg,#241914,#0f766e)",
    shortDesc: "چسبندگی بالا، مناسب هوای سرد و خشک.",
    description: "رزین تیره با چسبندگی بالا که در فصل‌های سرد و خشک، کشش بهتری روی سیم ایجاد می‌کند.",
    specs: [
      { label: "نوع", value: "رزین تیره" },
      { label: "مناسب برای", value: "ویولن و ویولنسل" },
    ],
  },
  {
    id: "p11",
    slug: "chaneh-gir-ergonomic",
    name: "چانه‌گیر ارگونومیک",
    category: "شانه و چانه‌گیر",
    price: 980,
    rating: 4.4,
    reviews: 18,
    stock: 25,
    gradient: "linear-gradient(140deg,#1c1c22,#0f766e)",
    shortDesc: "راحتی بیشتر در جلسات تمرین طولانی.",
    description: "طراحی ارگونومیک که فشار روی گردن و فک را در تمرین‌های طولانی کاهش می‌دهد.",
    specs: [
      { label: "جنس", value: "چوب آبنوس" },
      { label: "قابلیت تنظیم", value: "دارد" },
    ],
  },
  {
    id: "p12",
    slug: "shaneh-quick-release",
    name: "شانه‌ی تاشوی سریع",
    category: "شانه و چانه‌گیر",
    price: 1150,
    rating: 4.5,
    reviews: 31,
    stock: 22,
    gradient: "linear-gradient(140deg,#7c93ff,#0f766e)",
    shortDesc: "نصب و جمع‌شدن سریع، مناسب جابه‌جایی مکرر.",
    description: "شانه‌ای سبک با مکانیزم تاشوی سریع، مناسب نوازندگانی که مدام ساز را جابه‌جا می‌کنند.",
    specs: [
      { label: "جنس", value: "کامپوزیت سبک" },
      { label: "قابلیت تنظیم ارتفاع", value: "دارد" },
    ],
  },
  {
    id: "p13",
    slug: "ketab-amoozesh-mabtadi",
    name: "کتاب آموزش ویولن، سطح مبتدی",
    category: "نت و آموزش",
    price: 420,
    rating: 4.7,
    reviews: 59,
    stock: 100,
    gradient: "linear-gradient(140deg,#0d9488,#1c1c22)",
    shortDesc: "گام‌به‌گام، همراه با تمرین‌های صوتی.",
    description: "کتابی جامع برای شروع یادگیری، با تمرین‌های تدریجی و کد QR برای دسترسی به فایل‌های صوتی.",
    specs: [
      { label: "سطح", value: "مبتدی" },
      { label: "تعداد صفحات", value: "۱۲۰ صفحه" },
    ],
  },
  {
    id: "p14",
    slug: "note-majmooe-concerto",
    name: "مجموعه نت کنسرتوهای منتخب",
    category: "نت و آموزش",
    price: 560,
    rating: 4.8,
    reviews: 27,
    stock: 45,
    gradient: "linear-gradient(140deg,#0f766e,#7c93ff)",
    shortDesc: "منتخب کنسرتوهای دوران رمانتیک.",
    description: "مجموعه‌ای از نت‌های کنسرتوهای محبوب دوران رمانتیک، مناسب هنرجویان سطح پیشرفته.",
    specs: [
      { label: "سطح", value: "پیشرفته" },
      { label: "تعداد قطعات", value: "۸ قطعه" },
    ],
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}
